@baseUrl = http://localhost:3000
@jwtToken = {{authLogin.response.body.accessToken}}

### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "wesley",
  "email": "wesley@email.com",
  "password": "123456"
}

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "wesley@email.com",
  "password": "123456"
}


### Update user
# @name updateUser
PATCH  {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "wesley",
  "email": "wesley@email.com"
}
